#!/bin/bash
#
# Show disassembed code along side tracer output
#
PROGRAM=$1

mem_addrs(){
    local prog=$1;
    readelf -S -W $prog \
        |grep "^ *\["|tail -n +2 \
        |cut -c8- \
        |grep "PROGBITS" \
        |awk '{print $1}' \
        |xargs -I{} objdump -S -j {} --prefix-addresses $prog \
        |egrep "^[a-f0-9]+ "|sed 's/^0*//'|awk '{print $1, $3, $4}'; }

join <(tracer $@|sort|uniq -c|sort -n|awk '{printf "%x %d\n", $2, $1}'|sort) \
     <(mem_addrs $PROGRAM|sort)|awk 'OFS="	" {print $1,$2,$3,$4}'
